### Authentication
POST {{host}}/api-token-auth/
Content-Type: application/json

{
  "username": "sudo",
  "password": "Admin@12345"
}

### Get all books
GET {{host}}/books/api/books/
#Authorization: Basic {{basic_auth_token}}
Authorization: Token {{auth_token}}
