# Generated by Django 5.2.1 on 2025-06-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_options_book_created_at_book_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(help_text="Number of pages in the book"),
        ),
    ]
